[package]
name = "morse_wav"
version = "0.0.1"
edition = "2024"

[dependencies]
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.40", features = ["derive"] }